
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.3.3
CC = gcc
CFLAGS = -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -Wno-unknown-pragmas -I/usr/include/libpng15    -DUSE_LCMS=1
LDFLAGS =  -lm lib/libimagequant.a -lpng15 -lm -lz  -lz  -llcms2 -lm  -lm
COCOA_READER = 0

